### ISSUE TITLE
Progress Tracking Card Creation

### ISSUE THREAD

**Issue by jarrah42** [bssw-psip/psip-automation#13]
As a project manager I want to use the results of the self-assessment to help me create progress tracking cards so that we can improve project practices.
=======================================================================

| **Parent** | **Children** | **Related** | **Blocks** | **Depends On** |
|------------|--------------|-------------|------------|----------------|
|            |              |             |            |                |

Acceptance Criteria:
--------------------
Once I have completed a self-assessment, I can create one or more PTCs. The tool will allow me to:
- [ ] Specify the title and description of the PTC
- [ ] Use the results of the self-assessment to establish a baseline for the PTC
- [ ] Use the results of the self-assessment to determine a series of goals that culminate in successful execution of the PTC
- [ ] Allow the PTC to be integrated into my existing tracking process, such as by saving it or transferring it to another format

Description, Additional Detail, Context:
---------------------------------------

Implemented By Task(s): 
-----------------------
- Task: *\<task url or ID\>*
